# Generated by Django 4.1.1 on 2022-09-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_alter_flight_destination_alter_flight_origin"),
    ]

    operations = [
        migrations.DeleteModel(name="Airport",),
    ]
